[manager]
need_libusb = true
usb_vid = 0x2c7c
usb_pid = 0x0125

# Uncomment the following if you need to change the modem detection timeout on
# resume and/or the time during which suspend is blocked after modem boot
#[suspend]
#boot_timeout = 120
#recovery_timeout = 9

[gpio]
dtr = 358
pwrkey = 35
reset = 68
apready = 231
disable = 232

[at]
uart = "/dev/ttyS2"
configure = [
# Each command has 4 possible elements:
#   * `cmd`   : the AT command itself, which will be translated to "AT+`cmd`"
#   * `subcmd`: the subcommand in case a single AT command can be used
#               to change multiple parameters, such as QCFG (optional)
#   * `value` : the commands, argument, usually used to set the value of
#               a specific parameter (optional)
#   * `expect`: the expected return value; the command is first executed
#               without any value in order to query the current state. This
#               state is then compared to the `expect` string; if they don't
#               match, the command is then executed with value `expect` in
#               order to set the parameter to the configured value (optional)
# A command can have `expect` OR `value` configured, but it shouldn't have both
    { cmd = "QGMR" },
    { cmd = "QDAI", expect = "1,1,0,1,0,0,1,1" },
    { cmd = "QCFG", subcmd = "risignaltype", expect = "\"physical\"" },
    { cmd = "QCFG", subcmd = "ims", expect = "1" },
    { cmd = "QCFG", subcmd = "urc/ri/ring", expect = "\"pulse\",2000,1000,5000,\"off\",1" },
    { cmd = "QCFG", subcmd = "urc/ri/smsincoming", expect = "\"pulse\",2000" },
    { cmd = "QCFG", subcmd = "urc/ri/other", expect = "\"off\",1" },
    { cmd = "QCFG", subcmd = "urc/delay", expect = "1" },
    { cmd = "QURCCFG", subcmd = "urcport", expect = "\"all\"" },
    { cmd = "QGPS", value = "1" },
    { cmd = "QSCLK", value = "1" },
    { cmd = "QCFG", subcmd = "urc/cache", value = "0" },
    { cmd = "EN_PCM48K" }
]
suspend = [
    { cmd = "QGPSEND" },
]
resume = [
    { cmd = "QGPS", value = "1" }
]
reset = [ { cmd = "CFUN", value = "1,1" } ]
