#!/bin/bash

adb shell 'echo Collecting dmesg... > /dev/kmsg'
adb shell dmesg > dmesg-modem.txt
adb pull /var/log/openqti.log

sudo sh -c 'echo Collecting dmesg... > /dev/kmsg'
dmesg > dmesg-pinephone.txt

journalctl -u eg25-manager.service -e > eg25-manager.log
journalctl -u ModemManager.service -e > modemmanager.log
journalctl -u NetworkManager.service -e > networkmanager.log

exit 0
