#!/bin/bash

TIMESTAMP=$(date "+%Y%m%d_%H%M%S")

get_persistent_logs(){

echo "  -> In case of persistent logging get logs of previous boot"

adb pull /persist/openqti.log.1
mv openqti.log.1 openqti-${TIMESTAMP}.log.1

journalctl -u eg25-manager.service -e --boot -1 > eg25-manager-${TIMESTAMP}.log.1
journalctl -u ModemManager.service -e --boot -1 > modemmanager-${TIMESTAMP}.log.1
journalctl -u NetworkManager.service -e --boot -1 > networkmanager-${TIMESTAMP}.log.1
}

adb shell 'echo Collecting dmesg... > /dev/kmsg'
adb shell dmesg > dmesg-modem-${TIMESTAMP}.txt
adb pull /var/log/openqti.log
mv openqti.log openqti-${TIMESTAMP}.log

sudo sh -c 'echo Collecting dmesg... > /dev/kmsg'
dmesg > dmesg-pinephone-${TIMESTAMP}.txt

journalctl -u eg25-manager.service -e > eg25-manager-${TIMESTAMP}.log
journalctl -u ModemManager.service -e > modemmanager-${TIMESTAMP}.log
journalctl -u NetworkManager.service -e > networkmanager-${TIMESTAMP}.log

get_persistent_logs

exit 0

