#!/bin/bash

TIMESTAMP=$(date "+%Y%m%d_%H%M%S")

get_persistent_logs(){

echo "  -> In case of persistent logging get logs of previous boot"

sudo sh -c "adb pull /persist/openqti-1.log"
[ -f "openqti-1.log" ] && sudo mv openqti-1.log openqti-1-${TIMESTAMP}.log

journalctl -u eg25-manager.service -e --boot -1 > eg25-manager-1-${TIMESTAMP}.log
journalctl -u ModemManager.service -e --boot -1 > modemmanager-1-${TIMESTAMP}.log
journalctl -u NetworkManager.service -e --boot -1 > networkmanager-1-${TIMESTAMP}.log
}

sudo sh -c "adb shell 'echo Collecting dmesg... > /dev/kmsg'"
sudo sh -c "adb shell dmesg > dmesg-modem-${TIMESTAMP}.txt"
sudo sh -c "adb pull /var/log/openqti.log"
[ -f "openqti.log" ] && sudo mv openqti.log openqti-${TIMESTAMP}.log

sudo sh -c 'echo Collecting dmesg... > /dev/kmsg'
sudo sh -c "dmesg > dmesg-pinephone-${TIMESTAMP}.txt"

journalctl -u eg25-manager.service -e > eg25-manager-${TIMESTAMP}.log
journalctl -u ModemManager.service -e > modemmanager-${TIMESTAMP}.log
journalctl -u NetworkManager.service -e > networkmanager-${TIMESTAMP}.log

get_persistent_logs

SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
/usr/bin/bash ${SCRIPT_DIR}/scrub_logs -t ${TIMESTAMP}

exit 0
