#!/bin/sh
# Just so you dont have to write.
# Reboot the modem into fastboot mode
# flash kernel + rootfs and reboot
echo -ne "AT+QFASTBOOT\r" > /dev/ttyUSB2
fastboot oem stay
fastboot flash aboot appsboot.mbn
fastboot reboot-bootloader
fastboot oem stay
fastboot flash:raw boot boot-mdm9607.img
fastboot flash:raw recovery recovery.img
fastboot flash system rootfs-mdm9607.ubi
fastboot flash recoveryfs recoveryfs.ubi
echo "Finished, if everything went well, run fastboot reboot to restart the modem"

