#!/bin/bash

if grep -q 1.1 /proc/device-tree/model
then
	DTR=358
else
	DTR=34
fi

for i in 35 68 231 232 $DTR
do
	[ -e /sys/class/gpio/gpio$i ] && continue
	echo $i > /sys/class/gpio/export || return 1
	echo out > /sys/class/gpio/gpio$i/direction || return 1
done
echo 1 > /sys/class/gpio/gpio232/value
echo 1 > /sys/class/gpio/gpio68/value && sleep 1 && echo 0 > /sys/class/gpio/gpio68/value 
#( echo 1 > /sys/class/gpio/gpio35/value && sleep 2 && echo 0 > /sys/class/gpio/gpio35/value ) || return 1
#sleep 10
#( echo 1 > /sys/class/gpio/gpio35/value && sleep 2 && echo 0 > /sys/class/gpio/gpio35/value ) || return 1
sleep 1
echo 0 > /sys/class/gpio/gpio232/value