#!/bin/sh
# Just so you dont have to write.
# Reboot the modem into fastboot mode
# flash kernel + rootfs into the recovery partitions and reboot
if grep -q 1.1 /proc/device-tree/model
then
	DTR=358
else
	DTR=34
fi

for i in 35 68 231 232 $DTR
do
	[ -e /sys/class/gpio/gpio$i ] && continue
	echo $i > /sys/class/gpio/export || return 1
	echo out > /sys/class/gpio/gpio$i/direction || return 1
done

echo 1 > /sys/class/gpio/gpio232/value
echo 1 > /sys/class/gpio/gpio68/value && sleep 1 && echo 0 > /sys/class/gpio/gpio68/value 
fastboot flash recovery mdm9607-boot.img
fastboot flash recoveryfs mdm9607-sysfs.ubi
echo 0 > /sys/class/gpio/gpio232/value && sleep 1
fastboot reboot
#echo 1 > /sys/class/gpio/gpio68/value && sleep 1 && echo 0 > /sys/class/gpio/gpio68/value